### ISSUE TITLE
Korporasjoner → 610 $2 bare

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#255]
Skilt ut fra fra #205 : Satellitter, romsonder, organisasjoner og andre korporasjoner som må(?) flyttes til 610 "Omtalt korporasjon" (eller evt. 110).

**Ferdig:**
- [x] `Active Cavity Radiometer Irradiance Monitor`
- [x] `Advanced Composition Explorer`
- [x] `Advanced Satellite for Cosmology and Astrophysics`
- [x] `Advanced Solar Observatory` 
- [x] `Baroniet Rosendal`
- [x] `Cerro Tololo Inter-American Observatory`
- [x] `Chandra`
- [x] `Conseil Européen pour la Recherche Nucléaire`
- [x] `COsmic Background Explorer`
- [x] `Datatilsynet`
- [x] `Elefantapoteket`
- [x] `Extreme Ultraviolet Explorer`
<s>- [ ] `Extremely Large Telescopes`</s>
- [x] `Harestua`: ligger som stedsterm, flyttes til 610 $0 [90259243](https://tools.wmflabs.org/bsaut/show/90259243) $a Solobservatoriet
- [x] `Herschel Space Observatory` + norsk: "Herschel-teleskopet" (#936)
- [x] `High Altitude Observatory`
- [x] `Infrared Astronomical Satellite`
- [x] `Infrared Space Observatory`
- [x] `International Space Station` + norsk: "Den internasjonale romstasjonen" (#985)
- [x] `International Ultraviolet Explorer`
- [x] `Jet Propulsion Laboratory`
- [x] `Konnerudverket`
- [x] `Large Earth-based Solar Telescope`
- [x] `Nordlysobservatorier` → `Nordlysobservatoriet`
- [x] [Nusse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005738)
- [x] `Skylab (romstasjon)`
- [x] `SOlar Heliospheric Observatory`
- [x] `Uninett`
- [x] `Verdens helseorganisasjon`

**Gjenstår – astro:**

*** Opprettet i BARE ***

- [x] `Cassini–Huygens` (romferd): Opprettet: [1542227320762](https://tools.wmflabs.org/bsaut/show/1542227320762)
- [x] `Europeiske observatorier` → `Extremely Large Telescope BF European Extremely Large Telescope`, opprettet [1542227320771](https://tools.wmflabs.org/bsaut/show/1542227320771)
- [x] `European Incoherent SCATter` (radarnettverk / vitenskapelig stiftelse): [4110698](https://tools.wmflabs.org/bsaut/show/4110698)
- [x] `Hipparcos` (satellitt): 610, opprettet [1542227320765](https://tools.wmflabs.org/bsaut/show/1542227320765)
- [x] `Solar-a` (japansk satellitt: 610, `Yohkoh BF Solar-A`): Opprettet [1542227320767](https://tools.wmflabs.org/bsaut/show/1542227320767) 
- [x] `Very Large Telescope Interferometer`: -> Very Large Telescope: [90986621](https://tools.wmflabs.org/bsaut/show/90986621)
- [x] `Wilkinson Microwave Anisotropy Probe` (WMAP, romsonde): Opprettet [1542227320770](https://tools.wmflabs.org/bsaut/show/1542227320770)

*** Slettet ***

- [x] `Columbus` (ISS-modul, romlaboratorium): 610? Opprette i BARE som "Columbus (ISS-modul)"?
- [x] `Heliosat ` (#924), programvare.
- [x] `LOFAR`: 610

*** Slette? ***

- [x] `Corrective Optics Space Telescope Axial Replacement`: Tssja, trenger vi denne? Holder kanskje med Hubble?
- [x] `Debrecen photoheliographic data` og `Debrecen photoheliographic results`: 
- [x] `Debrecen photoheliographic results` ->`Debrecen Photoheliographic Data` … eller observatoriet?
- [x] `EUV imaging spectrometer` ?
- [x] `Faint Object Spectrograph`
- [x] `Hard X-Ray Burst Spectrometer` (#1005)
- [x] `Kuiper Airborne Observatory`
- [x] `Lunar Laser Ranging experiment`
- [x] `Meteosat`
- [x] `Spacelab`
- [x] `Xmm-newton` -> `XMM-Newton`

**Gjenstår – annet:**

- [x] `Burroughs`
- [x] `CODASYL`
- [x] `Cray`
- [x] `IBM`
- [x] `International conference on software engineering`
- <s> [ ] `Large Hadron Collider`?</s> Nei, denne er ikke korporasjon: http://id.loc.gov/authorities/subjects/sh85074708.html
- [x] `Motorola`
- [x] [Norsk data](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010497​)
- [x] `Scientific Committee on Antarctic Research` -> `Den vitenskapelige komité for antarktisforskning`

**Omtalt verk?**

- [x] `Almagest`

**Comment by danmichaelo** [comment]
Mal:

```
almar --diffs replace \
  '650 #7 $$a Conseil Européen pour la Recherche Nucléaire $$2 noubomn' \
  '610 27 $$a European Organization for Nuclear Research $$2 bare'
```

**Comment by BioHeidi** [comment]
Hva skjer med denne listen?

**Comment by danmichaelo** [comment]
Den blir laaaaangre og langre

**Comment by danmichaelo** [comment]
men den blir litt kortere også innimellom

**Comment by danmichaelo** [comment]
Large Hadron Collider: LC har den som 650 (http://id.loc.gov/authorities/subjects/sh85074708.html), men skjønner ikke helt hvorfor.

Finner ikke noen passende kategorier på https://www.loc.gov/marc/ambiguous-headings.html .. laboratories er 610, experiment stations er 610
